config/routes.rb
BlogFeed::Application.routes.draw do
  

  root :to => 'main#index'
  match 'resume', :to => "resume#resume"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get '/resume/*title', :to => "resume#category", as: 'category'

  resources :resume do
    resource :category
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :title, :experience_ids, :education_highlight_ids
  validates_presence_of :title
  validates_uniqueness_of :title
  has_many :experience_categories, :dependent => :destroy
  has_many :experiences, :through => :experience_categories, :order => "end_date DESC, start_date ASC"
  has_many :education_categories, :dependent => :destroy
  has_many :education_highlights, :through => :education_categories
  accepts_nested_attributes_for :experiences, :education_highlights
end

app/models/education.rb
class Education < ActiveRecord::Base
  attr_accessible :end_date, :location, :name, :start_date, :education_highlight_ids, :education_highlights_attributes
  validates_presence_of :name
  has_many :education_highlights, :dependent => :destroy
  accepts_nested_attributes_for :education_highlights, :allow_destroy => true
end

app/models/education_category.rb
class EducationCategory < ActiveRecord::Base
  attr_accessible :category_id, :education_highlight_id
  belongs_to :category
  belongs_to :education_highlight
end

app/models/education_highlight.rb
class EducationHighlight < ActiveRecord::Base
  attr_accessible :education_id, :highlight, :category_ids
  validates_presence_of :highlight
  has_many :education_categories, :dependent => :destroy
  has_many :categories, :through => :education_categories
  belongs_to :education
  accepts_nested_attributes_for :education, :categories
end

app/models/experience.rb
class Experience < ActiveRecord::Base
  attr_accessible :description, :end_date, :location, :position, :start_date, :title, :category_ids
  validates_presence_of :title
  has_many :experience_categories, :dependent => :destroy
  has_many :categories, :through => :experience_categories
  accepts_nested_attributes_for :categories
  scope :ordered, order("title ASC")
end

app/models/experience_category.rb
class ExperienceCategory < ActiveRecord::Base
  attr_accessible :category_id, :experience_id
  belongs_to :experience
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  @categories = Category.order("title ASC")

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  	@categories = Category.order("title ASC")
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def resume
    @categories = Category.order("title ASC")
  end

  def category
    #Note: need to fix routes to be accessed by filters bar

    @categories = Category.order("title ASC")

    @category_all = Category.find_all_by_title(params[:title].split('/'))

    @educ_combined = []
    @category_all.each do |category|
      category.education_highlights.each do |highlight|
        @educ_combined.push(highlight.education)
      end
    end
    @educ_combined = @educ_combined.uniq

    @exp_combined = []
    @category_all.each do |category|
      category.experiences.each do |experience|
        @exp_combined.push(experience)
      end
    end
    @exp_combined = @exp_combined.uniq

    @title = "Resume"
  end 
end

  def cat_educ(category)
    educations = []
      category.education_highlights.each do |highlight|
        educations.push(highlight.education)
      end
      educations = educations.uniq
      return educations
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
	def cat_educ(category)
		educations = []
    	category.education_highlights.each do |highlight|
    		educations.push(highlight.education)
   		end
    	educations = educations.uniq
    	return educations
	end
end

app/views/layouts/_header.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Example Resume", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
  </ul>
  <section class="top-bar-section">
    <ul class="right">
      <li class="divider"></li>
      <li><%= link_to "Home", root_path %></li>
      <li class="divider"></li>
      <li class="has-dropdown"><a href="#">Resume</a>
        <ul class="dropdown">
          <li><%= link_to "General Information", resume_path %></li>
          <li><label>Specfic Resumes</label></li>
          <% @categories.each do |category| %>
            <li><%= link_to category.title, category_path(:title => category.title) %></li>
          <% end %>
        </ul>
      </li>
    </ul>
  </section>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

    <header>

    <%= render 'layouts/header' %>

  </header>

  <body>

    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/main/index.html.erb
<h1>Main#index</h1>
<p>Find me in app/views/main/index.html.erb</p>

<p>Highlights and so forth can go here<p>

app/views/resume/_education.html.erb
<h4><%= education.name %></h4>
<h5><%= education.location unless education.location.nil? %></h5>
<ul class="disc">
	<% education.education_highlights.each do |highlight| %>
		<% if highlight.categories.include? category %>
			<li><%= highlight.highlight %></li>
		<% end %>
	<% end %>
</ul>

app/views/resume/_experience.html.erb
<h4>
	<%= experience.position unless experience.position.nil? %>
</h4>
<h5>
	<%= experience.title %><%= ", " + experience.location unless experience.location.nil? %>
</h5>
<h6>
	<%= experience.start_date.strftime('%B %Y') unless experience.start_date.nil? %>
	<%= " - " + experience.end_date.strftime('%B %Y') unless experience.end_date.nil? %>
</h6>
<p><%= experience.description unless experience.description.nil?%></p>

app/views/resume/_heading.html.erb
<h2>Andrew Linford</h2>
<h5>jalinford@gmail.com</h5>
<h6>Cell phone: (415) 226-8461<h6>
<h2></h2>

app/views/resume/_sub_nav.html.erb
<dl class="sub-nav">
  <dt>Resumes:</dt>
  <dd class="<%= 'active' if @category_all.nil? %>" ><%= link_to "Info", resume_path %></dd>
  <% @categories.each do |category| %>
		<dd class="<%= 'active' if @category_all.include?(category) %>"><%= link_to category.title, category_path(:title => category.title) %></dd>
	<% end %>
</dl>

app/views/resume/category.html.erb
<%= render 'sub_nav' %>
<%= render "heading" %>

<h1>Combined if needed (other below)</h2>

<h3>Education</h3>
	<% @educ_combined.each do |education| %>
	<h4><%= education.name %></h4>
	<h5><%= education.location unless education.location.nil? %></h5>
	<ul class="disc">
		<% education.education_highlights.each do |highlight| %>
			<% if highlight.categories.any? { |x| @category_all.include?(x) } %>
				<li><%= highlight.highlight %></li>
			<% end %>
		<% end %>
	</ul>
<% end %>

<h3>Previous Experience</h3>
<% @exp_combined.each do |experience| %>
	<h4><%= experience.position unless experience.position.nil? %></h4>
	<h5><%= experience.title %><%= ", " + experience.location unless experience.location.nil? %></h5>
	<h6><%= experience.start_date.strftime('%B %Y') unless experience.start_date.nil? %>
	<%= " - " + experience.end_date.strftime('%B %Y') unless experience.end_date.nil? %></h6>
	<p><%= experience.description unless experience.description.nil?%></p>
<% end %>

<% @category_all.each do |category| %>

	<h2>Category = <%= category.title %> </h2>

	<h3>Education</h3>
	<% cat_educ(category).each do |education| %>
		<%= render 'education', :education => education, :category => category %>
	<% end %>

	<h3>Previous Experience</h3>
	<% category.experiences.each do |experience| %>
		<%= render 'experience', :experience => experience %>
	<% end %>

<% end %>

app/views/resume/resume.html.erb
<%= render 'sub_nav' %>

<h1>Please click on the resume you wish to see</h1>

<% @categories.each do |category| %>
	<h2><%= link_to category.title, category_path(:title => category.title) %></h2>
<% end %>